// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kqivmzrhwoajidwykoho.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtxaXZtenJod29hamlkd3lrb2hvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc1MzAwOTQsImV4cCI6MjA3MzEwNjA5NH0.mcAni6Qk_lO9r3TUpO5vvB5J4-pTSgCI_OgDgEWzFeY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});